### ISSUE TITLE
--watch does not take imported files into account

### ISSUE THREAD

**Issue by jleclanche** [dahlia/libsass-python#155]
Same issue as https://github.com/Kronuz/pyScss/issues/86

```scss
// main.scss
@import "base.scss";
```

Running `sassc --watch main.scss main.css` and modifying `base.scss` will not regenerate `main.css`.

**Comment by sveetch** [comment]
libsass-python is just a wrapper around libsass, the watch command is something at higher level, i don't remember sassc-ruby implemented a watch command yet.

And so libsass-python watch command is not very advanced, i think it may even disappear in future because a strong watch command (as the one from Compass or node-sass) is something hard to implement correctly.

I may recommend you to use an additional tool that correctly implement a watch mode, (as the one from Compass), like my Boussole tool or others, some of them are listed in comments of #115

**Comment by jleclanche** [comment]
IMHO if a --watch flag is implemented it should work as expected. I think it's absolutely fair not to implement it in libsass-python, but then it shouldnt be there at all.

**Comment by asottile** [comment]
libsass doesn't expose this information, without some hacky regex / reparsing or libsass exposing internals we won't be able to properly implement this.  I would like to remove `--watch` since it's not functional for most scss codebases.  @dahlia thoughts?  we could point people to something that _does_ work in the documentation.

**Comment by jleclanche** [comment]
Imported files aside, can you somehow get a list of the entire sass tree? It seems like a feature libsass should expose.

**Comment by asottile** [comment]
I'm not sure what you mean by "sass tree"?  Do you mean the filesystem or the total sass contents?

**Comment by jleclanche** [comment]
The total contents. But now that I think about it I guess it's the same thing as the import tree...

**Comment by asottile** [comment]
Yeah, libsass would have to expose the internals to get that -- which it doesn't.

**Comment by dahlia** [comment]
Unless libsass provides the import tree we'd like to remove `--watch` option.  Before completely remote the option, we should write about the limitations of the `--watch` option, and mark it deprecated in the docs.

**Comment by asottile** [comment]
`--watch` has been deprecated and will be removed in a future version #156
