### ISSUE TITLE
sassutils strip_extension not specified

### ISSUE THREAD

**Issue by mmessmore** [dahlia/libsass-python#284]
I get the following warning using sassutils:

```
.../lib/python3.7/site-packages/sassutils/builder.py:157: FutureWarning: `strip_extension` was not specified, defaulting to `False`.
  In the future, `strip_extension` will default to `True`.
```

**Comment by pikesley** [comment]
https://xkcd.com/979/

**Comment by asottile** [comment]
@pikesley is there something you don't understand about the warning?

**Comment by dannykomo** [comment]
I have a troble that I cannot google out a way how to specify the `strip_extension` when usining the "on deploy" aproach as described here: https://sass.github.io/libsass-python/frameworks/flask.html#building-sass-scss-for-each-deployment

It is important to find a solution because, one they change the default value of the `strip_extension`, my web app will break after deploy.

**Comment by asottile** [comment]
@dannykomo the format of that is specified [here](https://sass.github.io/libsass-python/sassutils/distutils.html)

**Comment by dannykomo** [comment]
@asottile thank you!!

I tried really hard to find answer to this without any success. So I think it would be nice to provide a link to the page you mentioned (i.e. `sassutils.distutils — setuptools/distutils integration`) from the page I mentioned (i.e. `Using with Flask`) or perhaps better directly from the main `libsass-python` page.
The problem is that on the `Using with Flask` the information is redundant to the page `sassutils.distutils — setuptools/distutils integration` and incomplete, but the `Using with Flask` page is so important because it is accessible via link named "Building Sass/SCSS for each deployment" from the main `libsass-python` page ([here](https://sass.github.io/libsass-python/index.html)) and the page you send me, that is far mor helpful, is not.

**Comment by asottile** [comment]
yeah I think the expectation is that you'd get to the SassMiddleware page somehow from there, maybe a link or two is missing
